import Foundation
import Testing

@testable import ScannyBoy

/// Reference values generated by `scipy.interpolate.PchipInterpolator`
/// against the same knots `ChannelCurve` builds, so the Swift editor's
/// on-canvas curve matches the Python `color.channel_curve` render.
@Suite("ChannelCurve")
struct ChannelCurveTests {
    private static let sampleTs: [Double] = [0.05, 0.125, 0.3, 0.5, 0.62, 0.8, 0.95]

    private func evaluate(
        _ offsets: (q1: Double, mid: Double, q3: Double)
    ) -> [Double] {
        let y = ChannelCurve.yKnots(offsets)
        let slopes = ChannelCurve.slopes(x: ChannelCurve.xKnots, y: y)
        return Self.sampleTs.map {
            ChannelCurve.evaluate(t: $0, x: ChannelCurve.xKnots, y: y, slopes: slopes)
        }
    }

    @Test("matches scipy's PchipInterpolator at (0.15, 0.1, 0.05)")
    func matchesScipyCaseOne() {
        let expected = [0.097066667, 0.229166667, 0.448533333, 0.6, 0.696, 0.84, 0.96]
        let actual = evaluate((q1: 0.15, mid: 0.1, q3: 0.05))
        for (a, e) in zip(actual, expected) {
            #expect(abs(a - e) < 1e-6)
        }
    }

    @Test("matches scipy's PchipInterpolator at (-0.2, 0.0, 0.2)")
    func matchesScipyCaseTwo() {
        let expected = [0.00232, 0.01375, 0.09392, 0.5, 0.75913088, 0.96672, 0.99768]
        let actual = evaluate((q1: -0.2, mid: 0.0, q3: 0.2))
        for (a, e) in zip(actual, expected) {
            #expect(abs(a - e) < 1e-6)
        }
    }

    @Test("matches scipy's PchipInterpolator at (0.2, -0.08, 0.0)")
    func matchesScipyCaseThree() {
        let expected = [0.13512, 0.31125, 0.44688, 0.42, 0.54102197, 0.805693793, 0.956223448]
        let actual = evaluate((q1: 0.2, mid: -0.08, q3: 0.0))
        for (a, e) in zip(actual, expected) {
            #expect(abs(a - e) < 1e-6)
        }
    }

    @Test("neutral offsets are the identity")
    func neutralIsIdentity() {
        let actual = evaluate((q1: 0, mid: 0, q3: 0))
        for (a, t) in zip(actual, Self.sampleTs) {
            #expect(abs(a - t) < 1e-6)
        }
    }

    @Test("identity above 1 passes display headroom through")
    func identityAboveOne() {
        #expect(ChannelCurve.evaluate(t: 1.4, offsets: (q1: 0.2, mid: -0.1, q3: 0.15)) == 1.4)
    }

    // MARK: - clampOffset

    @Test("an in-range offset is unchanged")
    func clampWithinRangePassesThrough() {
        let clamped = ChannelCurve.clampOffset(0.05, at: 1, other: (q1: 0, mid: 0, q3: 0))
        #expect(abs(clamped - 0.05) < 1e-9)
    }

    @Test("an offset beyond ±0.2 is bounded to the max")
    func clampBoundsToOffsetMax() {
        let high = ChannelCurve.clampOffset(5, at: 0, other: (q1: 0, mid: 0, q3: 0))
        let low = ChannelCurve.clampOffset(-5, at: 2, other: (q1: 0, mid: 0, q3: 0))
        #expect(abs(high - ChannelCurve.offsetMax) < 1e-9)
        #expect(abs(low - (-ChannelCurve.offsetMax)) < 1e-9)
    }

    @Test("dragging mid below q1 clamps to the minimum gap above it")
    func clampEnforcesOrderingAboveLowerNeighbor() {
        // q1 = 0.2 -> knot y = 0.45. Pushing mid's knot down to 0.3 would
        // leave only a 0.05 gap; forcing it to -1 should stop at the
        // largest offset the ±0.2 bound still allows, and never drop the
        // gap below CURVE_MIN_GAP.
        let other = (q1: 0.2, mid: 0.0, q3: 0.0)
        let clamped = ChannelCurve.clampOffset(-1, at: 1, other: other)
        let y = ChannelCurve.yKnots((q1: other.q1, mid: clamped, q3: other.q3))
        #expect(y[2] - y[1] >= ChannelCurve.minGap - 1e-9)
    }

    @Test("dragging mid above q3 clamps to the minimum gap below it")
    func clampEnforcesOrderingBelowUpperNeighbor() {
        let other = (q1: 0.0, mid: 0.0, q3: -0.2)
        let clamped = ChannelCurve.clampOffset(1, at: 1, other: other)
        let y = ChannelCurve.yKnots((q1: other.q1, mid: clamped, q3: other.q3))
        #expect(y[3] - y[2] >= ChannelCurve.minGap - 1e-9)
    }

    @Test("clamping never produces a gap smaller than CURVE_MIN_GAP, across a sweep")
    func clampNeverViolatesMinGap() {
        for q1 in stride(from: -0.2, through: 0.2, by: 0.1) {
            for q3 in stride(from: -0.2, through: 0.2, by: 0.1) {
                for proposed in stride(from: -1.0, through: 1.0, by: 0.2) {
                    let clamped = ChannelCurve.clampOffset(proposed, at: 1, other: (q1: q1, mid: 0, q3: q3))
                    #expect(abs(clamped) <= ChannelCurve.offsetMax + 1e-9)
                    let y = ChannelCurve.yKnots((q1: q1, mid: clamped, q3: q3))
                    #expect(y[1] - y[0] >= ChannelCurve.minGap - 1e-9)
                    #expect(y[2] - y[1] >= ChannelCurve.minGap - 1e-9)
                    #expect(y[3] - y[2] >= ChannelCurve.minGap - 1e-9)
                    #expect(y[4] - y[3] >= ChannelCurve.minGap - 1e-9)
                }
            }
        }
    }
}
